baseURL = "http://lehrerbildung.github.io/"
languageCode = "en-us"
title = "BKD"


theme = "hugo-learn-theme"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "bildung" 
  
[[menu.shortcuts]] 
	name = "<i class='fab fa-github'></i> Github Content"
	identifier = "content"
	url = "https://github.com/Lehrerbildung/BKD"
	weight = 10

[[menu.shortcuts]] 
	name = "<i class='fab fa-github'></i> Github Website"
	identifier = "website"
	url = "https://github.com/Lehrerbildung/Lehrerbildung.github.io"
	weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

